 "use client";
import {useState} from "react";import {generateWeek,compatibleSwaps} from "@/lib/engine/planner";import {MealType} from "@/lib/types";
const slots:MealType[]=["breakfast","lunch","snack","dinner"];
export default function Home(){const[week,setWeek]=useState(generateWeek());const[selected,setSelected]=useState<{d:number;s:MealType}|null>(null);const[done,setDone]=useState<Record<string,boolean>>({});
function swap(id:string){if(!selected)return;const{d,s}=selected;const m=compatibleSwaps(week[d].day,s).find(x=>x.id===id);if(!m)return;setWeek(w=>w.map((x,i)=>i===d?{...x,meals:{...x.meals,[s]:m}}:x));setSelected(null)}
return <main className="min-h-screen"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><div><b className="text-xl text-[var(--primary)]">HealthOS</b><div className="text-xs text-[var(--muted)]">Personal nutrition & recovery system</div></div><button className="rounded-xl bg-[var(--primary)] px-4 py-2 text-sm font-semibold text-white" onClick={()=>setWeek(generateWeek())}>Regenerate</button></div></header>
<section className="mx-auto max-w-7xl px-5 py-8"><div className="mb-7 grid gap-4 md:grid-cols-4">{[["Weight","58.0 kg","Gradual gain"],["Recovery","64%","WHOOP baseline"],["Sleep","6h 54m","Target 7h30m+"],["Protein","90–100g","Daily target"]].map(x=><div className="card p-5" key={x[0]}><div className="text-xs font-semibold uppercase text-[var(--muted)]">{x[0]}</div><div className="metric mt-2 text-2xl font-bold">{x[1]}</div><div className="text-xs text-[var(--muted)]">{x[2]}</div></div>)}</div>
<h1 className="text-3xl font-bold">This week's plan</h1><p className="mb-6 mt-1 text-[var(--muted)]">Swap meals freely. Tuesday is pure vegetarian.</p>
<div className="grid gap-5 lg:grid-cols-2">{week.map((day,di)=><article className="card p-5" key={day.date}><div className="mb-4 flex justify-between"><div><b className="text-lg">{day.day}</b><div className="text-xs text-[var(--muted)]">{day.date}{day.day==="Tuesday"?" · Pure vegetarian":""}</div></div></div>
<div className="space-y-3">{slots.map(s=>{const m=day.meals[s],k=day.date+s;return <div className="rounded-2xl border border-[var(--border)] p-4" key={k}><div className="flex justify-between"><span className="text-xs font-semibold uppercase text-[var(--muted)]">{s}</span><button className={`rounded-full px-3 py-1 text-xs ${done[k]?"bg-[var(--accent)]":"bg-gray-100"}`} onClick={()=>setDone(x=>({...x,[k]:!x[k]}))}>{done[k]?"✓ Eaten":"Mark eaten"}</button></div><div className="mt-2 font-semibold">{m.name}</div><div className="text-xs text-[var(--muted)]">{m.calories} kcal · {m.protein}g protein · {m.fibre}g fibre</div><button className="mt-2 text-sm font-semibold text-[var(--primary)] underline" onClick={()=>setSelected({d:di,s})}>Change meal</button></div>})}</div></article>)}</div></section>
{selected&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/30 p-4 md:items-center"><div className="w-full max-w-xl rounded-3xl bg-white p-6"><div className="mb-4 flex justify-between"><b>Choose alternative</b><button onClick={()=>setSelected(null)}>Close</button></div>{compatibleSwaps(week[selected.d].day,selected.s).map(m=><button key={m.id} onClick={()=>swap(m.id)} className="mb-2 w-full rounded-2xl border p-4 text-left"><b>{m.name}</b><div className="text-xs text-[var(--muted)]">{m.calories} kcal · {m.protein}g protein · {m.carbs}g carbs · {m.fat}g fat · {m.fibre}g fibre</div></button>)}</div></div>}</main>}